version: '2.3'

services:


  mysqlhoneypot:
    container_name: mysqld
    restart: always
    network_mode: "host"
    image: "hary654321/mysqld"
    volumes:
     - $PWD/data/mysql/log:/var/log/mysqld
    environment:
      HP_LOG_PATH: "/var/log/mysqld/mysqld.json"
