version: '2.3'

services:


  mysqlhoneypot:
    container_name: mysqld
    restart: always
    network_mode: "host"
    image: "hary654321/mysql"
    volumes:
     - $PWD/data/mysql/log:/var/log/mysql
    environment:
      HP_LOG_PATH: "/var/log/mysql/mysql.json"
